### PR TITLE
[#49] Service ID used as key ID in signatures

### LINKED ISSUE #49: [BUG] Service ID used as key ID in signatures
**Describe the bug**
Service IDs are currently being used as the key ID when constructing the signature authorization header. This is no longer a valid approach, as there may be multiple keypairs associated with a service account. 

**Expected behavior**
We should use the public key fingerprint (SHA256) as the key ID instead to enable us identify the appropriate key to use for signature verification.

### PR DESCRIPTION
**Pull request by roberlander2**
## Description
This PR changes the behavior of the `KeyId` field in `SignatureAuthHeader`. This field now contains the SHA256 fingerprint of a signing service's public key instead of its service ID.

**Resolves #49**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires updating the documentation.
- [x] I have made necessary changes to the documentation.
- [x] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

File: sigauth/signature.go [hunk 1]
```diff
@@ -154,16 +158,40 @@ func (s *SignatureAuth) CheckRequestServiceSignature(r *Request, requiredService
...
+		requiredServiceIDs = s.serviceRegManager.SubscribedServices()
+	}
+
+	for _, serviceID := range requiredServiceIDs {
+		serviceReg, err = s.serviceRegManager.GetServiceRegWithPubKey(serviceID)
+		if err != nil {
+			return "", fmt.Errorf("failed to retrieve service pub key: %v", err)
+		}
+
+		fingerprint, err = authutils.GetKeyFingerprint(&s.serviceKey.PublicKey)
```
Comment (shurwit) [inline sigauth/signature.go:174]: The `ServiceReg.PubKey` should actually have this key ID computed and cached in the `Kid` field. Feel free to update naming for consistency, but we should avoid the redoing fingerprint operation unnecessarily as it is not super cheap.

**Review by shurwit — COMMENTED** [review]
Thanks @roberlander2, looking good! Just one comment below

File: sigauth/signature.go [hunk 2]
```diff
@@ -116,7 +116,11 @@ func (s *SignatureAuth) SignRequest(r *http.Request) error {
 
 	headers := []string{"request-line", "host", "date", "digest", "content-length"}
 
-	sigAuthHeader := SignatureAuthHeader{KeyID: s.serviceRegManager.AuthService.ServiceID, Algorithm: "rsa-sha256", Headers: headers}
+	serviceReg, err := s.serviceRegManager.GetServiceRegWithPubKey(s.serviceRegManager.AuthService.ServiceID)
+	if err != nil {
+		return fmt.Errorf("failed to retrieve service registration: %v", err)
+	}
```
Comment (shurwit) [inline sigauth/signature.go:122]: There is no guarantee that the signature being generated is using a key associated with a service reg record. Here we need to use the fingerprint of the `s.serviceKey` directly rather than using service reg records.

**Review by shurwit — COMMENTED** [review]
Thanks @roberlander2, one more comment below

**Review by shurwit — APPROVED** [review]
Thanks @roberlander2, LGTM!
